var gender = [
	  'Cis-gender woman',
	  'Woman',
	  'Transgender Woman',
	  'Woman of Trans experience',
	  'Woman with a history of gender transition',
	  'Trans feminine',
	  'Feminine-of-center',
	  'MTF (male-to-female)',
	  'Demigirl',
	  'T-girl',
	  'Transgirl',
	  'Sistergirl',
	  'Cis-gender man',
	  'Man',
	  'Transgender man',
	  'Man of Trans experience',
	  'Man with a history of gender transition',
	  'Trans masculine',
	  'Masculine-of-center',
	  'FTM (female-to-male)',
	  'Demiboy',
	  'T-boy',
	  'Transguy',
	  'Brotherboy',
	  'Trans',
	  'Transgender',
	  'Transsexual',
	  'Non-binary',
	  'Genderqueer',
	  'Agender',
	  'Xenogender',
	  'Fem',
	  'Femme',
	  'Butch',
	  'Boi',
	  'Stud',
	  'Aggressive (AG)',
	  'Androgyne',
	  'Tomboy',
	  'Gender outlaw',
	  'Gender non-conforming',
	  'Gender variant',
	  'Gender fluid',
	  'Genderfuck',
	  'Bi-gender',
	  'Multi-gender',
	  'Pangender',
	  'Gender creative',
	  'Gender expansive',
	  'Third gender',
	  'Neutrois',
	  'Omnigender',
	  'Polygender',
	  'Graygender',
	  'Intergender',
	  'Maverique',
	  'Novigender',
	  'Two-spirit',
	  'Hijra',
	  'Kathoey',
	  'Muxe',
	  'Khanith/Xanith',
	  'X-gender',
	  'MTX',
	  'Bakla',
	  'Mahu',
	  'Fa’afafine',
	  'Waria',
	  'Palao’ana',
	  'Ashtime',
	  'Mashoga',
	  'Mangaiko',
	  'Chibados',
	  'Tida wena',
	  'Bixa’ah',
	  'Alyha',
	  'Hwame',
	  'Lhamana',
	  'Nadleehi',
	  'Dilbaa',
	  'Winkte',
	  'Ninauposkitzipxpe',
	  'Machi-embra',
	  'Quariwarmi',
	  'Chuckchi',
	  'Whakawahine',
	  'Fakaleiti',
	  'Calabai',
	  'Calalai',
	  'Bissu',
	  'Acault',
	  'Travesti',
	  'Questioning',
	  'I don’t use labels',
	  'Declined',
	  'Not listed'
	  ]
function ran_gen(){
	var randomnumber = Math.floor(Math.random() * (gender.length));
	document.getElementById('random_gender').innerHTML = gender[randomnumber];
}
function search_on_bing(){
	let searchText = document.getElementById("random_gender").textContent;
	        let encodedText = encodeURIComponent(searchText);
	
	        // 构造 BING 搜索 URL 并跳转
	        let url = "https://www.bing.com/search?q=性别%20" + encodedText;
	        window.location.href = url;
}

